/** Same-origin routes available to browser code. Upstream URLs stay server-only. */
export const apiRoutes = {
  auth: {
    exists: "/api/auth/exists",
    login: "/api/auth/login",
    google: "/api/auth/google",
    logout: "/api/auth/logout",
    session: "/api/auth/session",
    phoneSend: "/api/auth/phone/send",
    phoneVerify: "/api/auth/phone/verify",
    signupSend: "/api/auth/signup/send",
    signupVerify: "/api/auth/signup/verify",
    forgotPasswordSend: "/api/auth/forgot-password/send",
    forgotPasswordVerify: "/api/auth/forgot-password/verify",
    forgotPasswordReset: "/api/auth/forgot-password/reset",
  },
  address: "/api/address",
  profile: "/api/profile",
  profileImage: "/api/profile/image",
  profileSummary: "/api/profile/summary",
  profileWallet: "/api/profile/wallet",
  profileWalletTransactions: "/api/profile/wallet/transactions",
  savedCards: "/api/profile/saved-cards",
  notificationSettings: "/api/profile/notifications",
  notifications: "/api/notifications",
  profileCoupons: "/api/profile/coupons",
  accountSecurity: {
    passwordSend: "/api/profile/security/password/send",
    passwordVerify: "/api/profile/security/password/verify",
    passwordUpdate: "/api/profile/security/password/update",
    deleteAccount: "/api/profile/security/delete",
  },
  orders: "/api/orders",
  favourites: "/api/favourites",
  restaurants: "/api/restaurants",
  deliveryProducts: "/api/deliveries/products",
  deliveryCart: "/api/deliveries/cart",
  deliveryCheckout: "/api/deliveries/checkout",
  vendorApplications: "/api/vendor-applications",
  orderReviews: "/api/orders/reviews",
  discovery: {
    shopTypes: "/api/deliveries/discovery/shop-types",
    banners: "/api/deliveries/discovery/banners",
    topBrands: "/api/deliveries/discovery/top-brands",
    nearbyStores: "/api/deliveries/discovery/nearby-stores",
    deals: "/api/deliveries/discovery/deals",
    orderAgain: "/api/deliveries/discovery/order-again",
  },
  maps: {
    places: "/api/maps/places",
    details: "/api/maps/place-details",
    reverse: "/api/maps/reverse",
  },
  contact: "/api/contact",
} as const;
